# This file contains platform and symbol configuration.
# Please note that this uses my personal OpenExchange token.
# Do not use this token for other purposes or share it with third parties.
# This file has not been added to .gitignor for your convenience

symbols:
  USDT: "USDT"
  BTCUSDT: "BTC"
  LTCUSDT: "LTC"
  TRXUSDT: "TRX"
  tBTCUSD: "BTC"
  tLTCUSD: "LTC"
  tTRXUSD: "TRX"

platforms:
  Bybit:
    url: "https://api-testnet.bybit.com/v5/market/tickers?category=linear&symbol={symbol}"
    symbols:
      - "BTCUSDT"
      - "TRXUSDT"

  Binance:
    url: "https://api.binance.com/api/v3/ticker/price?symbol={symbol}"
    symbols:
      - "BTCUSDT"
      - "TRXUSDT"
      - "LTCUSDT"

  BitFinex:
    url: "https://api-pub.bitfinex.com/v2/ticker/{symbol}"
    symbols:
      - "tBTCUSD"
      - "tTRXUSD"
      - "tLTCUSD"

  Solarpath:
    url: "https://api.solarpath.io/v1/9b1fce5cbcb0d19b6af32821d3b2d2e5/price2usd/{symbol}"
    symbols:
      - "USDT"

exchangers:
  Openexchange:
    url: "https://openexchangerates.org/api/latest.json?app_id=7b448cdc0755442696c2663505022082"
